#!/usr/bin/env bash
# This Bash script configures Nginx so that its HTTP response
# contains a custom header.
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
