#!/bin/bash
# This bash script installs and configures HAproxy on my lb-01 server
# The code below updates the system packages to the latest
apt update -y
# The code below installs HAproxy
apt install haproxy -y
#The code below configures a HAproxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
	log /dev/log local10
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 20s
	user haproxy
	group haproxy

defaults
	log     global
	mode    http
	option  httplog
	timeout connect 5000
	timeout server  50000

backend servers
	balance roundrobin
	server [318460]-web-01 [318460]-web-01:80 check
	server [318460]-web-02 [318460]-web-02:80 check
EOF

#The code below enables HAproxy init script
sed-i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

#The part below restarts the HAproxy
service haproxy restart
