#!/bin/bash
# This bash script installs and configures HAproxy on my lb-01 server
# The code below updates the system packages
sudo apt-get update
# The code below installs HAproxy
sudo apt-get install -y haproxy
#The code below configures a HAproxy

echo "
frontend http-in
	bind *:80
	default_backend web_servers

backend web_servers
	server 323649-web-01 100.26.178.116:80 check
	server 323649-web-02 54.144.154.1:80 check
	balance roundrobin
" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
