#!/usr/bin/env bash
# This script loops from 1 to 10 and:

#displays bad luck for the 4th iteration of the loop
#displays good luck for the 8th iteration of the loop
#displays Best School for the other iterations

counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 3 ]
	then
		echo "bad luck"
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( counter++ ))
done
