#!/usr/bin/env bash
#This script that displays all active IPv4 IPs on the machine it’s executed on.

the_active_ips=$(ip addr show | grep 'inet ' | awk '{print $2}' | cut -d '/' -f 1)

echo "The active IPv4 IPs are:"
echo "$the_active_ips"
